package com.github.nivance.test.entity;

public class PersonWithBLOBs extends PersonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.firstname
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    private String firstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column person.surname
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.firstname
     *
     * @return the value of person.firstname
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.firstname
     *
     * @param firstname the value for person.firstname
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column person.surname
     *
     * @return the value of person.surname
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column person.surname
     *
     * @param surname the value for person.surname
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PersonWithBLOBs other = (PersonWithBLOBs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getFirstname() == null ? other.getFirstname() == null : this.getFirstname().equals(other.getFirstname()))
            && (this.getSurname() == null ? other.getSurname() == null : this.getSurname().equals(other.getSurname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getFirstname() == null) ? 0 : getFirstname().hashCode());
        result = prime * result + ((getSurname() == null) ? 0 : getSurname().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbggenerated Sat Nov 21 10:14:39 CST 2015
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", firstname=").append(firstname);
        sb.append(", surname=").append(surname);
        sb.append("]");
        return sb.toString();
    }
}